#######################################################
# Kubernetes + Istio deployment for ERP
#######################################################

kind: RouteRule
metadata:
  name: my-rule
spec:
  destination:
    name: lw-erp
  # match:
  #   httpHeaders:
  #     uri:
  #       prefix: /erp
  rewrite:
    uri: /
  route:
  - labels:
      version: v1
    weight: 100
